name: Python without OpenSSL CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libffi-dev libgdbm-dev libncurses5-dev libsqlite3-dev zlib1g-dev libbz2-dev libreadline-dev liblzma-dev

    - name: Download and compile Python without OpenSSL
      run: |
        PYTHON_VERSION=3.9.1  # Change this to your desired version
        wget https://www.python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tgz
        tar -xzf Python-$PYTHON_VERSION.tgz
        cd Python-$PYTHON_VERSION
        ./configure --without-ssl
        make
        sudo make altinstall  # altinstall to avoid replacing the default python binary

    - name: Verify Python installation
      run: |
        /usr/local/bin/python3.9 -c "import ssl; print(ssl.HAS_SSL)"  # This should fail if OpenSSL is correctly disable
