name: Python with and without OpenSSL CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libffi-dev libgdbm-dev libncurses5-dev libsqlite3-dev zlib1g-dev libbz2-dev libreadline-dev liblzma-dev

    - name: Download and compile Python without OpenSSL
      run: |
        PYTHON_VERSION=3.9.1  # Change this to your desired version
        wget https://www.python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tgz
        tar -xzf Python-$PYTHON_VERSION.tgz
        cd Python-$PYTHON_VERSION
        ./configure --without-ssl
        make
        sudo make altinstall  # altinstall to avoid replacing the default python binary

    - name: Verify Python installation without OpenSSL
      run: |
        /usr/local/bin/python3.9 -c "import ssl; print(ssl.OPENSSL_VERSION)"  # This should raise an error or return False
      continue-on-error: true

    - name: Install and configure OpenSSL
      run: |
        mkdir -p $HOME/openssl && cd $HOME/openssl
        wget https://www.openssl.org/source/openssl-1.1.1l.tar.gz
        tar -xzvf openssl-1.1.1l.tar.gz
        cd openssl-1.1.1l
        ./config --prefix=/home/runner/openssl --openssldir=/home/runner/openssl shared zlib
        make
        make test
        make install
        echo "export PATH=$HOME/openssl/bin:$PATH" >> $GITHUB_ENV
        echo "export LD_LIBRARY_PATH=/home/runner/openssl/lib" >> $GITHUB_ENV
        echo "export LC_ALL=en_US.UTF-8" >> $GITHUB_ENV
        echo "export LDFLAGS='-L/home/runner/openssl/lib -Wl,-rpath,/home/runner/openssl/lib'" >> $GITHUB_ENV
        echo "export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/runner/openssl/lib/" >> $GITHUB_ENV

    - name: Download and compile Python with OpenSSL
      run: |
        cd $GITHUB_WORKSPACE
        PYTHON_VERSION=3.9.1  # Adjust as needed
        wget https://www.python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tgz
        tar -xzf Python-$PYTHON_VERSION.tgz
        cd Python-$PYTHON_VERSION
        ./configure --prefix=/home/runner/Python39/ --with-openssl=/home/runner/openssl
        make
        make install

    - name: Verify Python installation with OpenSSL
      run: |
        /home/runner/Python39/bin/python3.9 -c "import ssl; print(ssl.OPENSSL_VERSION)"  # This should return True
