name: Without OpenSSL CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libffi-dev libgdbm-dev libncurses5-dev libsqlite3-dev zlib1g-dev libbz2-dev libreadline-dev liblzma-dev

    - name: Download and compile Python without OpenSSL
      run: |
        PYTHON_VERSION=3.9.1  # Adjust this to your desired version
        wget https://www.python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tgz
        tar -xzf Python-$PYTHON_VERSION.tgz
        cd Python-$PYTHON_VERSION
        ./configure --without-ssl
        make
        sudo make altinstall  # altinstall to avoid replacing the default python binary

    - name: Check Python version and OpenSSL status
      run: |
        /usr/local/bin/python3.9 --version
        /usr/local/bin/python3.9 -m sysconfig | grep -i openssl

    - name: Verify Python installation without OpenSSL
      run: |
        /usr/local/bin/python3.9 -c "import ssl; print('OpenSSL version:', ssl.OPENSSL_VERSION)"  # This should raise an error
      continue-on-error: true

    - name: Diagnostic step - List Python installations
      run: |
        which -a python3.9
        ls -l /usr/local/bin/python*
